### ISSUE TITLE
Normal maps turn to yellow when exported

### ISSUE THREAD

**Issue by ronage** [ptasev/Ego-Engine-Modding#15]
How can I prevent this from happening? They are blue before exporting.

**Comment by Ryder25** [comment]
I'll need more info.  What program are you using? What game? What file have you tried to export? Maybe even send reference files so I can reproduce the issue.

**Comment by ronage** [comment]
I am using photoshop cs2 and the intel dds plugin. All the _n.dds files in F1 2017 are normal maps as I suppose and they are all blue tinted when they are opened in erp ego archiver. When I open them in photoshop they are yellow tinted. Putting them back into the erp file with import textures leaves them yellow. 

I suppose they won’t work then in the game anymore. I wanted to do some stitching 3D effect on the career drivers cap but didn’t work.

**Comment by Ryder25** [comment]
What format are you using to save the dds file?
