### ISSUE TITLE
MipMaps are incorrectly modded.

### ISSUE THREAD

**Issue by harrrystanley** [ptasev/Ego-Engine-Modding#23]
I am new to helmet modding, I've watched some tutorials and followed them exactly. I have managed to get a downloaded helmet working, but when I modify it slightly. ERP comes up with MipMaps are incorrectly modded. What am I doing wrong? Thanks

**Comment by Ryder25** [comment]
It could be that the erp file that you downloaded was done incorrectly. You should start with the original erp file, and modify that one with your new dds texture.
