### ISSUE TITLE
M3rc3d35

### ISSUE THREAD

**Issue by Deletd05052019** [ptasev/Ego-Engine-Modding#31]
Where is the file for Mercedes?

**Comment by Deletd05052019** [comment]
For F1 2018

**Comment by Deletd05052019** [comment]
I'm talking about the mercedes.vtf.xml file, the mercedes.erp file can't have it

**Comment by Deletd05052019** [comment]
Oh yeah I found this website that answers everything thanks creater of this mod
https://www.racedepartment.com/downloads/f1-2018-any-teams-always-start-last-or-first.27021/

**Comment by ptasev** [comment]
I don't actually mod the games so I can't help you with this. Looks like you found the solution.
