### ISSUE TITLE
F1 2020 Erpfragment type 16 is not supported

### ISSUE THREAD

**Issue by TractionDistraction** [ptasev/Ego-Engine-Modding#33]
[](url)
![image](https://user-images.githubusercontent.com/67924899/86629666-a8382080-bfc3-11ea-8973-c319ed38400c.png)

**Comment by XOOLHP** [comment]
I know, I had the same problem as you, I am waiting for more data to try to be able to extract the models, it is annoying, it is the only defect that I criticize for the moment ...

**Comment by TractionDistraction** [comment]
Its in the usual path but instead of animation package you can find it in team package and Team Livery.

They have repacked everything differently this year..I don't like it...

**Comment by XOOLHP** [comment]
I don't like it either, so it's the same source I have, but I have "uncommon", I hope we can modify the skin, it will be really a shame to be restrained

**Comment by TractionDistraction** [comment]
I think it all correlates with this podium pass (Hence the common, uncommon, legendary, etc) 

I don't think it was worth adding this podium pass in, I hope its not just bound for Online only. 

If we can get past this hurdle we should be back to where we were before.

**Comment by XOOLHP** [comment]
I don't know, I'm watching this midi at home, all I hope is to be able to settle this problem of "erpfragment type 16" that would make insertion more interesting!
From what I read, other files should have arrived at the official release on the 10th, while waiting for those who have it have a semi complete version

**Comment by ptasev** [comment]
I uploaded a new version of the erp archiver.  Give it a try.

**Comment by XOOLHP** [comment]
great guy thank you it's perfect !! Provenance : Courrier pour Windows 10 De : Petar TasevEnvoyé le :jeudi 9 juillet 2020 05:34À : ptasev/Ego-Engine-ModdingCc : XOOLHP; CommentObjet :Re: [ptasev/Ego-Engine-Modding] F1 2020 Erpfragment type 16 is not supported (#33) I uploaded a new version of the erp archiver. Give it a try.—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by treybillingsley** [comment]
I downloaded .NET Core 3.1 but it still says that I need to download it when I try to open the app.

**Comment by XOOLHP** [comment]
Did you download the latest version of Ego? And did you take version 64?
