### ISSUE TITLE
Crashing when pressing arrows in TexArrayIndex

### ISSUE THREAD

**Issue by MrCosta7** [ptasev/Ego-Engine-Modding#34]
![image](https://user-images.githubusercontent.com/58045573/87073415-453dc800-c215-11ea-8dcd-6d9aa234925f.png)
Whenever I press that arrow on a texture array with more than 1 texture, the application crashes. Running as admin doesn't fix it.

**Comment by ptasev** [comment]
This should be fixed in version 7.1.

**Comment by MrCosta7** [comment]
Awesome! But now I get this when I try to replace any of the arrays. Any ideas? 
![image](https://user-images.githubusercontent.com/58045573/87234127-e23f6300-c3c5-11ea-8d0a-6d90c8d64194.png)

**Comment by ptasev** [comment]
Send me the dds file you are trying to import.

**Comment by MrCosta7** [comment]
This is what I'm trying to import. Can't upload .dds files here so it's in .png.
![Jaguar](https://user-images.githubusercontent.com/58045573/87234891-5598a300-c3cd-11ea-8607-7189008e9ebc.png)

**Comment by Ryder25** [comment]
I need the dds specifically.

**Comment by ptasev** [comment]
I need the dds specifically.

**Comment by MrCosta7** [comment]
Jaguar dds.rar
https://www61.zippyshare.com/v/bWHUpYu4/file.html

**Comment by MrCosta7** [comment]
Well it's solved somehow. I used an online converter and now it works.

**Comment by ptasev** [comment]
I also noticed that you were using DXT1 for your dds, when the existing sponsor texture is BC7 srgb.
