### ISSUE TITLE
installed dotnet - says it isn't installed

### ISSUE THREAD

**Issue by Forsti37** [ptasev/Ego-Engine-Modding#36]

**Comment by ptasev** [comment]
Have you tried again with 7.1? If the problem persists, please show an image of the error you're getting. Also, open cmd or powershell and run the command `dotnet --list-runtimes` and show me the output.

**Comment by callum1859** [comment]
I am having same issue with Version 7.1
Ran Command Prompt:
C:\Users\Callum>dotnet --list-runtimes
Microsoft.AspNetCore.App 3.1.0-preview1.19508.20 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 3.1.5 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 5.0.0-preview.6.20312.15 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 3.1.0-preview1.19506.1 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 3.1.5 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 5.0.0-preview.6.20305.6 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 3.1.0-preview1.19506.1 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 3.1.5 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 5.0.0-preview.6.20308.1 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by Ryder25** [comment]
Can you try with the x64 version of the .NET Core runtime?

**Comment by ptasev** [comment]
Can you try with the x64 version of the .NET Core runtime?

**Comment by callum1859** [comment]
Thank you it worked
