### ISSUE TITLE
Files not showing up

### ISSUE THREAD

**Issue by EVO323** [ptasev/Ego-Engine-Modding#37]
When I try to set the game directory when I navigate to the folder they are in they don't appear and when I try using open to edit the files they end up at a smaller resolution (128 x 128 max) ruining the designs

**Comment by EVO323** [comment]
![image](https://user-images.githubusercontent.com/46874740/87216154-ad61dc00-c2f1-11ea-8d03-ab85eb34a4f2.png)

**Comment by ptasev** [comment]
This needs to be the location of your F1 2020 game folder.

**Comment by EVO323** [comment]
Thanks!
