### ISSUE TITLE
Couldn't preview the image of the emblem in f1 2020

### ISSUE THREAD

**Issue by ilyaszak** [ptasev/Ego-Engine-Modding#41]
When Im using EEA 7.1 and trying to preview the emblem it states: "Couldn't create a preview! Unable to load DLL 'libzstd' or one of its dependencies. The specified module could not be found. (0x8007007E).

I also installed NET Core just before using this app, so it might be linked to the fact that I used the wrong link for the download. So please tell me what should I do!

**Comment by ptasev** [comment]
See issue #44
