### ISSUE TITLE
Can't open EEA

### ISSUE THREAD

**Issue by S0umrak** [ptasev/Ego-Engine-Modding#42]
Every time I try and launch EEA I keep getting an error saying I need to install .NET Core. I have installed .NET Core 3.1.6 but it continually gives me this prompt.

Edit: I've also tried the 7.0 version and it gives me the same issue. 

![Screenshot_1](https://user-images.githubusercontent.com/38537019/89092997-7036ba00-d384-11ea-9d0a-4599e99824d5.png)

**Comment by Uthrid** [comment]
I had this problem but it turned out i had installed the wrong .NET Core installer, I accidentally installed the x86 version so i uninstalled that version and installed the x64 version and it worked then.
Give it a try and see if that works.

**Comment by Flowerdoggo** [comment]
So i tried this, had the x64 and x86 none of them worked for 3.1 and 5.0 any other ideas? It seems like it cant find its path to it.

> I had this problem but it turned out i had installed the wrong .NET Core installer, I accidentally installed the x86 version so i uninstalled that version and installed the x64 version and it worked then.
> Give it a try and see if that works.

**Comment by S0umrak** [comment]
> I had this problem but it turned out i had installed the wrong .NET Core installer, I accidentally installed the x86 version so i uninstalled that version and installed the x64 version and it worked then.
> Give it a try and see if that works.

I only downloaded the x86 versions. Tried installing the .NET Core Runtime, Desktop Runtime, ASP.NET Core Runtime, and the SDK. None of which worked

**Comment by Flowerdoggo** [comment]
Well even restarting my computer didnt work sadly, i dont know what to do, maybe install an older version of EEA?

**Comment by S0umrak** [comment]
> Well even restarting my computer didnt work sadly, i dont know what to do, maybe install an older version of EEA?

only versions 7.0 and 7.1 are compatible with F1 2020, which is what I'm trying to work with. I got older versions to work, but I don't need them.

**Comment by Flowerdoggo** [comment]
> > Well even restarting my computer didnt work sadly, i dont know what to do, maybe install an older version of EEA?
> 
> only versions 7.0 and 7.1 are compatible with F1 2020, which is what I'm trying to work with. I got older versions to work, but I don't need them.

Well Yeah that's why i want it aswell, there is a discord made by the creator and i am trying my luck there but no one seems to have this problem.

**Comment by S0umrak** [comment]
Update: Tried on a second PC I have. Still no luck. My main PC is a AMD Ryzen based system, the other being an Intel based system.

**Comment by Flowerdoggo** [comment]
> Update: Tried on a second PC I have. Still no luck. My main PC is a AMD Ryzen based system, the other being an Intel based system.

Yeah I have an Intel based one

**Comment by S0umrak** [comment]
> > Update: Tried on a second PC I have. Still no luck. My main PC is a AMD Ryzen based system, the other being an Intel based system.
> 
> Yeah I have an Intel based one

I didn't think it would be an issue pertaining to AMD based systems, but I wanted a sanity check anyway. Just can't seem to figure out why both systems have the same issue.

**Comment by Flowerdoggo** [comment]
I think there is a problem with the path to the .net core that needs fixing or it cant seem to find it anywhere

**Comment by S0umrak** [comment]
And now it works for me. I installed Microsoft Visual Studio and the components related to .NET Core (as well as others I'd like to play around with and learn), and now EEA 7.1 is working, seemingly as intended.

**Comment by Flowerdoggo** [comment]
> And now it works for me. I installed Microsoft Visual Studio and the components related to .NET Core (as well as others I'd like to play around with and learn), and now EEA 7.1 is working, seemingly as intended.

Okay yeah for me it works aswell but I know why, you had to scroll down a little and then install the x64 windows OS Desktop runtime

**Comment by S0umrak** [comment]
> > And now it works for me. I installed Microsoft Visual Studio and the components related to .NET Core (as well as others I'd like to play around with and learn), and now EEA 7.1 is working, seemingly as intended.
> 
> Okay yeah for me it works aswell but I know why, you had to scroll down a little and then install the x64 windows OS Desktop runtime

Interesting. I'll try that on my other PC, see if it works

**Comment by S0umrak** [comment]
> > > And now it works for me. I installed Microsoft Visual Studio and the components related to .NET Core (as well as others I'd like to play around with and learn), and now EEA 7.1 is working, seemingly as intended.
> > 
> > 
> > Okay yeah for me it works aswell but I know why, you had to scroll down a little and then install the x64 windows OS Desktop runtime
> 
> Interesting. I'll try that on my other PC, see if it works

Yup, works on both my PCs now.
