### ISSUE TITLE
Cannot Create Preview

### ISSUE THREAD

**Issue by ghost** [ptasev/Ego-Engine-Modding#44]
Using Ego ERP Archiver for F1 2020 mods.

When I come to open any of the textures I get the message:
'Could not create preview! Export/Import may still work in certain circumstances. 
Unable to load DLL "libzstd" or one of its dependencies: The specified module could not be found. (0x8007007E)

Any help very appreciated, cheers

**Comment by ptasev** [comment]
Sounds like the files weren't extracted correctly from the zip file. The file structure should look like this:
![image](https://user-images.githubusercontent.com/23424044/92665455-78571300-f2bb-11ea-8282-c0c27f162faf.png)

**Comment by axlnevaeh** [comment]
Hi, my structure looks exactly the same as the picture, but it still doesn't work. what can i do?

**Comment by ptasev** [comment]
What is the texture format that you're trying to view? Preview is not supported for some texture formats.

**Comment by axlnevaeh** [comment]
it is in tif i believe

**Comment by ptasev** [comment]
Can you show a screenshot of the app when you're previewing the texture?

**Comment by axlnevaeh** [comment]
![Capture](https://user-images.githubusercontent.com/75633897/101393884-c4ebc380-3895-11eb-9fb5-f67181327245.PNG)

**Comment by Ryder25** [comment]
Do you have libzstd in the x64, or x86 folders? Also, are you using Windows 64 bit?

**Comment by ptasev** [comment]
Do you have libzstd in the x64, or x86 folders? Also, are you using Windows 64 bit?

**Comment by axlnevaeh** [comment]
yes i have it in both folders and im using 64 bit

**Comment by ptasev** [comment]
Hmm, I'm not really sure what else to check. It may be that zlib has a dependency that you don't have that could maybe be checked by Dependency Walker, or maybe the app doesn't have permission to access the dll? I'm not sure.

**Comment by axlnevaeh** [comment]
oh wow thank you that worked! thanks so much

**Comment by axlnevaeh** [comment]
um, do you have any idea why it cant find the files when i use import? Im doing a custom livery for f1 2020, but when i click import on the folder that i downloaded (which contains the car mods and everything), it just shows the folder to be blank
