### ISSUE TITLE
Could not import texture error

### ISSUE THREAD

**Issue by ProfessorEff** [ptasev/Ego-Engine-Modding#48]
Made a custom helmet for F1 2020 and all textures have imported correctly except for the in fom01_helmet.erp. The fom01_helmet_d.tif comes up with an error message saying "Unable to read beyond the end of the stream." when I try to  import it.

**Comment by ptasev** [comment]
I'll need the relevant files to reproduce the error myself. For example the erp file, the mipmaps file if applicable, and the dds file you are trying to import. It would be ideal if you can give the files with the proper folder hierarchy.

**Comment by ProfessorEff** [comment]
I’ve attached the screenshot of the error and the file I’m trying to import.

It’s in the fom01_helmet.erp located here Steam\steamapps\common\F1 2020\2020_asset_groups\character_package\team_livery\fom01

The error occurs after I try to import the file but before I could import the mipmaps. Importing worked for all other parts of the helmet in this erp and in the fom01.erp and fom01_gloves.erp. It’s just this one exact file.

**Comment by ptasev** [comment]
It doesn't seem like the file or screenshot actually got attached. You may have to attach them on the github website instead of sending an email.

Also, I don't own the F1 2020 game so I'll need the erp file too.

**Comment by ProfessorEff** [comment]
Ah, here you go.
[Import Error Files.zip](https://github.com/ptasev/Ego-Engine-Modding/files/5476520/Import.Error.Files.zip)

**Comment by ptasev** [comment]
The dds file is completely empty and has no data.

**Comment by ProfessorEff** [comment]
Weird. I exported it again in photoshop and it seems to have worked this time. But the dds worked for the two other erp files. I've imported the new one across all 3.

**Comment by ptasev** [comment]
That's odd, I'm not sure what could have happened. I'm glad you got it working now.
