### ISSUE TITLE
I can't open the .erp file on Photoshop

### ISSUE THREAD

**Issue by qDARK212** [ptasev/Ego-Engine-Modding#52]
I can't open the .erp file on Photoshop. What can I do?

**Comment by ptasev** [comment]
You need to use the Ego ERP Archiver to open the erp. The erp contains texture files. It will help you extract a dds file from the erp which you can then modify in Photoshop. (assuming you have a dds plugin for photoshop)

**Comment by qDARK212** [comment]
Thanks I will try that! I didn't had the dds plugin for Photoshop so that's why I think it didn't work.

**Comment by qDARK212** [comment]
I can't install the dds plugin

**Comment by ptasev** [comment]
I can't help you with that. I don't own Photoshop.

**Comment by qDARK212** [comment]
K thanks for help
