### ISSUE TITLE
Error when trying to export

### ISSUE THREAD

**Issue by IssaRevioli** [ptasev/Ego-Engine-Modding#53]
![image](https://user-images.githubusercontent.com/78236645/106331098-a5b15700-6284-11eb-80a0-e85e86bbb7f5.png)

I'm trying to access the cornering file in the ai vehicle_performance folder in F1 2020 but i'm getting this error when trying to export.
Is this a limitation of the program or just some kind of bug?

**Comment by ptasev** [comment]
I don't own F1 2020. Can you send the particular erp file you're working with so I can see what's going on?

**Comment by IssaRevioli** [comment]
[very_low.zip](https://github.com/ptasev/Ego-Engine-Modding/files/5896591/very_low.zip)

**Comment by ptasev** [comment]
Looks like it's actually pkg file. What happens is over the years they change the same file between different formats. Some games use xml for cornering and some use the pkg format.  One of these days I need to look into an automatic solution for detecting the file type.

For now you can manually convert it to json, and back to pkg file using the Ego File Converter. Use the Resources -> Export to get the file out, and import to put it back in to erp.

**Comment by IssaRevioli** [comment]
Thank you
