### ISSUE TITLE
cant dl EGO ERP ARCHIVER

### ISSUE THREAD

**Issue by Xeffee** [ptasev/Ego-Engine-Modding#59]
Hi, I cant dl EGO ERP ARCHIVER when i dl and want open the winrar the file automaticly download or when i arrive to open the winrar and want extract a file was missing.
Thanks for listening, im frecnh so sorry for my bad language.
I let you a DM on racedepartement but i open a issue here.
Xeffe

**Comment by ptasev** [comment]
I'm having a tough time understanding what you mean.  Maybe add some pictures to give me an idea of what you're doing, or write the steps you take to try and run the app.

**Comment by Xeffee** [comment]
![Capture ego](https://user-images.githubusercontent.com/82341569/114371140-7cfce600-9b80-11eb-97d2-32e9995bffc1.PNG)
error while uploading

**Comment by Xeffee** [comment]
an answaer ?

**Comment by ptasev** [comment]
I'm not sure why you're getting an error.  Maybe a browser extension is screwing something up. Try a different browser.

**Comment by Xeffee** [comment]
thanks that good when i change the browser
