### ISSUE TITLE
Unable to open game directory

### ISSUE THREAD

**Issue by Lefoxxxx** [ptasev/Ego-Engine-Modding#62]
The menu is broken and I don't know how to fix it 
![image](https://user-images.githubusercontent.com/95043918/143476856-45a677ce-9e3d-4a0e-b6ca-5626b7796f9c.png)
as soon as I try to click on the menu it disapears

**Comment by ptasev** [comment]
If you're trying to to set the directory you have to click the `Set Directory` menu item.  Clicking the empty one won't do anything.
