### ISSUE TITLE
Erro CTF FILE EGO EDITOR

### ISSUE THREAD

**Issue by douglasdrs22** [ptasev/Ego-Engine-Modding#66]
when I open the ctf file the error appears

The file could not be opened!
array dimensions have exceeded accepted range

I use W10 
I install Net frameork required

https://uploaddeimagens.com.br/imagens/qh64S6E

**Comment by douglasdrs22** [comment]
F1 2014

**Comment by ptasev** [comment]
You need to click the Formula 1 tab before opening the file.
